/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../../app/routing/__root'
import { Route as LayoutRouteImport } from './../../app/routing/_layout'
import { Route as LayoutSettingsRouteImport } from './../../app/routing/_layout/settings'
import { Route as LayoutDocsRouteImport } from './../../app/routing/_layout/docs'
import { Route as LayoutAuthRouteImport } from './../../app/routing/_layout/auth'
import { Route as LayoutProtectedRouteImport } from './../../app/routing/_layout/_protected'
import { Route as LayoutProtectedIndexRouteImport } from './../../app/routing/_layout/_protected/index'
import { Route as LayoutProtectedSearchRouteImport } from './../../app/routing/_layout/_protected/search'
import { Route as LayoutProtectedResyncRouteImport } from './../../app/routing/_layout/_protected/resync'
import { Route as LayoutProtectedRepoIdRouteImport } from './../../app/routing/_layout/_protected/repo/$id'
import { Route as LayoutProtectedPullRequestIdRouteImport } from './../../app/routing/_layout/_protected/pull-request/$id'
import { Route as LayoutProtectedProjectIdRouteImport } from './../../app/routing/_layout/_protected/project/$id'
import { Route as LayoutProtectedIssueCreateRouteImport } from './../../app/routing/_layout/_protected/issue/create'
import { Route as LayoutProtectedIssueIdRouteImport } from './../../app/routing/_layout/_protected/issue/$id'
import { Route as LayoutProtectedRepoIdPullRequestsRouteImport } from './../../app/routing/_layout/_protected/repo/$id/pull-requests'
import { Route as LayoutProtectedRepoIdProjectsRouteImport } from './../../app/routing/_layout/_protected/repo/$id/projects'
import { Route as LayoutProtectedRepoIdIssuesRouteImport } from './../../app/routing/_layout/_protected/repo/$id/issues'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDocsRoute = LayoutDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuthRoute = LayoutAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProtectedRoute = LayoutProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProtectedIndexRoute = LayoutProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutProtectedRoute,
} as any)
const LayoutProtectedSearchRoute = LayoutProtectedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => LayoutProtectedRoute,
} as any)
const LayoutProtectedResyncRoute = LayoutProtectedResyncRouteImport.update({
  id: '/resync',
  path: '/resync',
  getParentRoute: () => LayoutProtectedRoute,
} as any)
const LayoutProtectedRepoIdRoute = LayoutProtectedRepoIdRouteImport.update({
  id: '/repo/$id',
  path: '/repo/$id',
  getParentRoute: () => LayoutProtectedRoute,
} as any)
const LayoutProtectedPullRequestIdRoute =
  LayoutProtectedPullRequestIdRouteImport.update({
    id: '/pull-request/$id',
    path: '/pull-request/$id',
    getParentRoute: () => LayoutProtectedRoute,
  } as any)
const LayoutProtectedProjectIdRoute =
  LayoutProtectedProjectIdRouteImport.update({
    id: '/project/$id',
    path: '/project/$id',
    getParentRoute: () => LayoutProtectedRoute,
  } as any)
const LayoutProtectedIssueCreateRoute =
  LayoutProtectedIssueCreateRouteImport.update({
    id: '/issue/create',
    path: '/issue/create',
    getParentRoute: () => LayoutProtectedRoute,
  } as any)
const LayoutProtectedIssueIdRoute = LayoutProtectedIssueIdRouteImport.update({
  id: '/issue/$id',
  path: '/issue/$id',
  getParentRoute: () => LayoutProtectedRoute,
} as any)
const LayoutProtectedRepoIdPullRequestsRoute =
  LayoutProtectedRepoIdPullRequestsRouteImport.update({
    id: '/pull-requests',
    path: '/pull-requests',
    getParentRoute: () => LayoutProtectedRepoIdRoute,
  } as any)
const LayoutProtectedRepoIdProjectsRoute =
  LayoutProtectedRepoIdProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => LayoutProtectedRepoIdRoute,
  } as any)
const LayoutProtectedRepoIdIssuesRoute =
  LayoutProtectedRepoIdIssuesRouteImport.update({
    id: '/issues',
    path: '/issues',
    getParentRoute: () => LayoutProtectedRepoIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutProtectedIndexRoute
  '/auth': typeof LayoutAuthRoute
  '/docs': typeof LayoutDocsRoute
  '/settings': typeof LayoutSettingsRoute
  '/resync': typeof LayoutProtectedResyncRoute
  '/search': typeof LayoutProtectedSearchRoute
  '/issue/$id': typeof LayoutProtectedIssueIdRoute
  '/issue/create': typeof LayoutProtectedIssueCreateRoute
  '/project/$id': typeof LayoutProtectedProjectIdRoute
  '/pull-request/$id': typeof LayoutProtectedPullRequestIdRoute
  '/repo/$id': typeof LayoutProtectedRepoIdRouteWithChildren
  '/repo/$id/issues': typeof LayoutProtectedRepoIdIssuesRoute
  '/repo/$id/projects': typeof LayoutProtectedRepoIdProjectsRoute
  '/repo/$id/pull-requests': typeof LayoutProtectedRepoIdPullRequestsRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutProtectedIndexRoute
  '/auth': typeof LayoutAuthRoute
  '/docs': typeof LayoutDocsRoute
  '/settings': typeof LayoutSettingsRoute
  '/resync': typeof LayoutProtectedResyncRoute
  '/search': typeof LayoutProtectedSearchRoute
  '/issue/$id': typeof LayoutProtectedIssueIdRoute
  '/issue/create': typeof LayoutProtectedIssueCreateRoute
  '/project/$id': typeof LayoutProtectedProjectIdRoute
  '/pull-request/$id': typeof LayoutProtectedPullRequestIdRoute
  '/repo/$id': typeof LayoutProtectedRepoIdRouteWithChildren
  '/repo/$id/issues': typeof LayoutProtectedRepoIdIssuesRoute
  '/repo/$id/projects': typeof LayoutProtectedRepoIdProjectsRoute
  '/repo/$id/pull-requests': typeof LayoutProtectedRepoIdPullRequestsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/_protected': typeof LayoutProtectedRouteWithChildren
  '/_layout/auth': typeof LayoutAuthRoute
  '/_layout/docs': typeof LayoutDocsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/_protected/resync': typeof LayoutProtectedResyncRoute
  '/_layout/_protected/search': typeof LayoutProtectedSearchRoute
  '/_layout/_protected/': typeof LayoutProtectedIndexRoute
  '/_layout/_protected/issue/$id': typeof LayoutProtectedIssueIdRoute
  '/_layout/_protected/issue/create': typeof LayoutProtectedIssueCreateRoute
  '/_layout/_protected/project/$id': typeof LayoutProtectedProjectIdRoute
  '/_layout/_protected/pull-request/$id': typeof LayoutProtectedPullRequestIdRoute
  '/_layout/_protected/repo/$id': typeof LayoutProtectedRepoIdRouteWithChildren
  '/_layout/_protected/repo/$id/issues': typeof LayoutProtectedRepoIdIssuesRoute
  '/_layout/_protected/repo/$id/projects': typeof LayoutProtectedRepoIdProjectsRoute
  '/_layout/_protected/repo/$id/pull-requests': typeof LayoutProtectedRepoIdPullRequestsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/docs'
    | '/settings'
    | '/resync'
    | '/search'
    | '/issue/$id'
    | '/issue/create'
    | '/project/$id'
    | '/pull-request/$id'
    | '/repo/$id'
    | '/repo/$id/issues'
    | '/repo/$id/projects'
    | '/repo/$id/pull-requests'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/docs'
    | '/settings'
    | '/resync'
    | '/search'
    | '/issue/$id'
    | '/issue/create'
    | '/project/$id'
    | '/pull-request/$id'
    | '/repo/$id'
    | '/repo/$id/issues'
    | '/repo/$id/projects'
    | '/repo/$id/pull-requests'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/_protected'
    | '/_layout/auth'
    | '/_layout/docs'
    | '/_layout/settings'
    | '/_layout/_protected/resync'
    | '/_layout/_protected/search'
    | '/_layout/_protected/'
    | '/_layout/_protected/issue/$id'
    | '/_layout/_protected/issue/create'
    | '/_layout/_protected/project/$id'
    | '/_layout/_protected/pull-request/$id'
    | '/_layout/_protected/repo/$id'
    | '/_layout/_protected/repo/$id/issues'
    | '/_layout/_protected/repo/$id/projects'
    | '/_layout/_protected/repo/$id/pull-requests'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/docs': {
      id: '/_layout/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof LayoutDocsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/auth': {
      id: '/_layout/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof LayoutAuthRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_protected': {
      id: '/_layout/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutProtectedRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_protected/': {
      id: '/_layout/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutProtectedIndexRouteImport
      parentRoute: typeof LayoutProtectedRoute
    }
    '/_layout/_protected/search': {
      id: '/_layout/_protected/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof LayoutProtectedSearchRouteImport
      parentRoute: typeof LayoutProtectedRoute
    }
    '/_layout/_protected/resync': {
      id: '/_layout/_protected/resync'
      path: '/resync'
      fullPath: '/resync'
      preLoaderRoute: typeof LayoutProtectedResyncRouteImport
      parentRoute: typeof LayoutProtectedRoute
    }
    '/_layout/_protected/repo/$id': {
      id: '/_layout/_protected/repo/$id'
      path: '/repo/$id'
      fullPath: '/repo/$id'
      preLoaderRoute: typeof LayoutProtectedRepoIdRouteImport
      parentRoute: typeof LayoutProtectedRoute
    }
    '/_layout/_protected/pull-request/$id': {
      id: '/_layout/_protected/pull-request/$id'
      path: '/pull-request/$id'
      fullPath: '/pull-request/$id'
      preLoaderRoute: typeof LayoutProtectedPullRequestIdRouteImport
      parentRoute: typeof LayoutProtectedRoute
    }
    '/_layout/_protected/project/$id': {
      id: '/_layout/_protected/project/$id'
      path: '/project/$id'
      fullPath: '/project/$id'
      preLoaderRoute: typeof LayoutProtectedProjectIdRouteImport
      parentRoute: typeof LayoutProtectedRoute
    }
    '/_layout/_protected/issue/create': {
      id: '/_layout/_protected/issue/create'
      path: '/issue/create'
      fullPath: '/issue/create'
      preLoaderRoute: typeof LayoutProtectedIssueCreateRouteImport
      parentRoute: typeof LayoutProtectedRoute
    }
    '/_layout/_protected/issue/$id': {
      id: '/_layout/_protected/issue/$id'
      path: '/issue/$id'
      fullPath: '/issue/$id'
      preLoaderRoute: typeof LayoutProtectedIssueIdRouteImport
      parentRoute: typeof LayoutProtectedRoute
    }
    '/_layout/_protected/repo/$id/pull-requests': {
      id: '/_layout/_protected/repo/$id/pull-requests'
      path: '/pull-requests'
      fullPath: '/repo/$id/pull-requests'
      preLoaderRoute: typeof LayoutProtectedRepoIdPullRequestsRouteImport
      parentRoute: typeof LayoutProtectedRepoIdRoute
    }
    '/_layout/_protected/repo/$id/projects': {
      id: '/_layout/_protected/repo/$id/projects'
      path: '/projects'
      fullPath: '/repo/$id/projects'
      preLoaderRoute: typeof LayoutProtectedRepoIdProjectsRouteImport
      parentRoute: typeof LayoutProtectedRepoIdRoute
    }
    '/_layout/_protected/repo/$id/issues': {
      id: '/_layout/_protected/repo/$id/issues'
      path: '/issues'
      fullPath: '/repo/$id/issues'
      preLoaderRoute: typeof LayoutProtectedRepoIdIssuesRouteImport
      parentRoute: typeof LayoutProtectedRepoIdRoute
    }
  }
}

interface LayoutProtectedRepoIdRouteChildren {
  LayoutProtectedRepoIdIssuesRoute: typeof LayoutProtectedRepoIdIssuesRoute
  LayoutProtectedRepoIdProjectsRoute: typeof LayoutProtectedRepoIdProjectsRoute
  LayoutProtectedRepoIdPullRequestsRoute: typeof LayoutProtectedRepoIdPullRequestsRoute
}

const LayoutProtectedRepoIdRouteChildren: LayoutProtectedRepoIdRouteChildren = {
  LayoutProtectedRepoIdIssuesRoute: LayoutProtectedRepoIdIssuesRoute,
  LayoutProtectedRepoIdProjectsRoute: LayoutProtectedRepoIdProjectsRoute,
  LayoutProtectedRepoIdPullRequestsRoute:
    LayoutProtectedRepoIdPullRequestsRoute,
}

const LayoutProtectedRepoIdRouteWithChildren =
  LayoutProtectedRepoIdRoute._addFileChildren(
    LayoutProtectedRepoIdRouteChildren,
  )

interface LayoutProtectedRouteChildren {
  LayoutProtectedResyncRoute: typeof LayoutProtectedResyncRoute
  LayoutProtectedSearchRoute: typeof LayoutProtectedSearchRoute
  LayoutProtectedIndexRoute: typeof LayoutProtectedIndexRoute
  LayoutProtectedIssueIdRoute: typeof LayoutProtectedIssueIdRoute
  LayoutProtectedIssueCreateRoute: typeof LayoutProtectedIssueCreateRoute
  LayoutProtectedProjectIdRoute: typeof LayoutProtectedProjectIdRoute
  LayoutProtectedPullRequestIdRoute: typeof LayoutProtectedPullRequestIdRoute
  LayoutProtectedRepoIdRoute: typeof LayoutProtectedRepoIdRouteWithChildren
}

const LayoutProtectedRouteChildren: LayoutProtectedRouteChildren = {
  LayoutProtectedResyncRoute: LayoutProtectedResyncRoute,
  LayoutProtectedSearchRoute: LayoutProtectedSearchRoute,
  LayoutProtectedIndexRoute: LayoutProtectedIndexRoute,
  LayoutProtectedIssueIdRoute: LayoutProtectedIssueIdRoute,
  LayoutProtectedIssueCreateRoute: LayoutProtectedIssueCreateRoute,
  LayoutProtectedProjectIdRoute: LayoutProtectedProjectIdRoute,
  LayoutProtectedPullRequestIdRoute: LayoutProtectedPullRequestIdRoute,
  LayoutProtectedRepoIdRoute: LayoutProtectedRepoIdRouteWithChildren,
}

const LayoutProtectedRouteWithChildren = LayoutProtectedRoute._addFileChildren(
  LayoutProtectedRouteChildren,
)

interface LayoutRouteChildren {
  LayoutProtectedRoute: typeof LayoutProtectedRouteWithChildren
  LayoutAuthRoute: typeof LayoutAuthRoute
  LayoutDocsRoute: typeof LayoutDocsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutProtectedRoute: LayoutProtectedRouteWithChildren,
  LayoutAuthRoute: LayoutAuthRoute,
  LayoutDocsRoute: LayoutDocsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
